<field:tabtartype itemname="分页栏类型" autofield="0" notsend="0" type="select" isnull="true" islist="0" default="1,2,3"  maxlength="250" page="">
</field:tabtartype>
<field:tabtarname itemname="分页栏名称" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tabtarname>
<field:tagname itemname="标签名" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tagname>
<field:activityimg itemname="活动图片" autofield="0" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activityimg>
<field:activitycondition itemname="活动条件" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitycondition>
<field:activitychangedate itemname="活动更新日期" autofield="0" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitychangedate>
<field:isactive itemname="是否卖光" autofield="0" notsend="0" type="radio" isnull="true" islist="0" default="是,否"  maxlength="250" page="">
</field:isactive>
<field:activitystartdate itemname="活动开始日期" autofield="0" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitystartdate>
<field:activityenddate itemname="活动结束日期" autofield="0" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activityenddate>
<field:activitynum itemname="活动名额" autofield="0" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitynum>
<field:activityintroduce itemname="活动简介" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activityintroduce>
<field:activityillustrate itemname="活动说明" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activityillustrate>
