<field:isnew itemname="是否是新活动" autofield="0" notsend="0" type="radio" isnull="true" islist="0" default="是,不是"  maxlength="250" page="">
</field:isnew>
<field:isactive itemname="是否抢光" autofield="0" notsend="0" type="radio" isnull="true" islist="0" default="是,不是"  maxlength="250" page="">
</field:isactive>
<field:datestart itemname="活动开始时间" autofield="0" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:datestart>
<field:dateend itemname="活动结束时间" autofield="0" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dateend>
<field:content itemname="活动内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:content>
