<?php
$z[0]=Array("body","	\r\n",0,153);
$z[0][4]['itemname']="文章内容";
$z[0][4]['autofield']="0";
$z[0][4]['notsend']="0";
$z[0][4]['type']="htmltext";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="";
$z[0][4]['page']="split";
$z[1]=Array("infotype","\r\n",157,307);
$z[1][4]['itemname']="联动";
$z[1][4]['autofield']="0";
$z[1][4]['notsend']="0";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>