<?php
$z[0]=Array("field","",493,516);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",517,543);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",584,613);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",653,711);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",8123,8158);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",10336,10374);
$z[5][4]['filename']="footer2.htm";
$z[6]=Array("global","",10412,10433);
$z[6][4]['name']="tongji";

?>