<field:tabtartype itemname="分页栏类型" autofield="0" notsend="0" type="select" isnull="true" islist="0" default="1,2,3"  maxlength="250" page="">
</field:tabtartype>
<field:tabtarname itemname="分页栏名称" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tabtarname>
<field:tagname itemname="标签名" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tagname>
<field:activityimg itemname="活动图片" autofield="0" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activityimg>

<field:activitycondition itemname="活动条件" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitycondition>


<field:activitychangedate itemname="活动更新日期" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:activitychangedate>
